<?php
$profile = $profile ?: ['username' => '', 'display_name' => '', 'headline' => '', 'bio' => ''];
$statusLabels = ['draft' => 'پیش‌نویس', 'open' => 'باز', 'in_progress' => 'در حال انجام', 'completed' => 'تکمیل‌شده', 'cancelled' => 'لغوشده'];
$invitationLabels = ['pending' => 'در انتظار پاسخ', 'accepted' => 'پذیرفته‌شده', 'declined' => 'ردشده'];
?>
<section class="dashboard-content">
  <div class="dashboard-heading employer-heading"><div><div class="eyebrow">فضای کاری کارفرما</div><h1>سلام، <?= e($profile['display_name'] ?: 'کارفرمای عزیز') ?> 👋</h1><p class="muted">پروژه‌تان را منتشر کنید و بهترین متخصص را انتخاب کنید.</p></div><a class="button button-light" href="#create-job">انتشار پروژه جدید ↗</a></div>
  <?php if ($message = Session::flash('success')): ?><div class="alert success">✅ <?= e($message) ?></div><?php endif; ?>
  <?php if ($message = Session::flash('error')): ?><div class="alert error">⚠️ <?= e($message) ?></div><?php endif; ?>
  <div class="stats-grid"><article class="stat-card"><strong class="stat-value"><?= count($jobs) ?></strong><span class="stat-label">پروژه‌های من</span></article><article class="stat-card"><strong class="stat-value"><?= count($invitations) ?></strong><span class="stat-label">دعوت‌های ارسال‌شده</span></article><article class="stat-card"><strong class="stat-value"><?= count($freelancers) ?></strong><span class="stat-label">فریلنسر فعال</span></article></div>
  <div class="dashboard-grid">
    <section class="dash-card" id="profile"><div class="card-title"><h2>پروفایل کسب‌وکار</h2><span>اعتماد بیشتر، همکاری بهتر</span></div><form method="post" action="<?= url('/dashboard/employer/profile') ?>"><?= csrf_field() ?><div class="form-row"><label>نام شرکت یا شخص<input name="display_name" value="<?= e($profile['display_name']) ?>" required></label><label>نام کاربری<input name="username" value="<?= e($profile['username']) ?>" required></label></div><label>عنوان فعالیت<input name="headline" value="<?= e($profile['headline']) ?>" placeholder="مثلاً استارتاپ فناوری"></label><label>درباره کسب‌وکار<textarea name="bio" rows="4" placeholder="کسب‌وکار و نیازهای خود را معرفی کنید..."><?= e($profile['bio']) ?></textarea></label><button class="button" type="submit">ذخیره پروفایل</button></form></section>
    <section class="dash-card" id="create-job"><div class="card-title"><h2>انتشار پروژه جدید</h2><span>پیدا کردن متخصص مناسب</span></div><form method="post" action="<?= url('/dashboard/employer/jobs') ?>"><?= csrf_field() ?><label>عنوان پروژه<input name="title" required placeholder="مثلاً طراحی وب‌سایت فروشگاهی"></label><label>توضیحات پروژه<textarea name="description" rows="4" required placeholder="شرح دقیق کار، خروجی‌ها و زمان‌بندی..."></textarea></label><div class="form-row"><label>حداقل بودجه<input type="number" name="budget_min" min="1" step="0.01" required placeholder="دلار"></label><label>حداکثر بودجه<input type="number" name="budget_max" min="1" step="0.01" required placeholder="دلار"></label></div><label>مهارت‌های موردنیاز<select name="skill_ids[]" multiple size="4"><?php foreach ($skills as $skill): ?><option value="<?= e($skill['id']) ?>"><?= e($skill['name']) ?></option><?php endforeach; ?></select></label><button class="button" type="submit">انتشار پروژه ↗</button></form></section>
  </div>
  <section class="dash-card jobs-card" id="jobs"><div class="card-title"><h2>پروژه‌های من</h2><span><?= count($jobs) ?> پروژه</span></div><?php foreach ($jobs as $job): ?><article class="job-item"><div class="job-info"><h3><?= e($job['title']) ?></h3><p><?= e(mb_strimwidth($job['description'], 0, 150, '…')) ?></p><small><span class="status status-<?= e($job['status']) ?>"><?= e($statusLabels[$job['status']] ?? $job['status']) ?></span> · <?= e($job['proposal_count']) ?> پیشنهاد · بودجه <?= e($job['budget_min']) ?> تا <?= e($job['budget_max']) ?> دلار</small></div></article><?php endforeach; ?><?php if (!$jobs): ?><p class="empty-state">هنوز پروژه‌ای منتشر نکرده‌اید.</p><?php endif; ?></section>
  <section class="dash-card" id="freelancers"><div class="card-title"><h2>فریلنسرهای فعال</h2><span>انتخاب متخصص مناسب</span></div><div class="freelancer-grid"><?php foreach ($freelancers as $freelancer): ?><article class="freelancer-item"><div class="freelancer-avatar"><?= e(mb_substr($freelancer['display_name'], 0, 1)) ?></div><h3><?= e($freelancer['display_name']) ?></h3><p><?= e($freelancer['headline'] ?: 'متخصص مستقل') ?></p><small><?= e($freelancer['hourly_rate'] ?: '—') ?> دلار/ساعت · <?= e($freelancer['availability'] === 'available' ? 'آماده همکاری' : 'مشغول') ?></small><?php if ($jobs): ?><details><summary class="text-link">ارسال پیشنهاد همکاری</summary><form class="proposal-form" method="post" action="<?= url('/dashboard/employer/invitations') ?>"><?= csrf_field() ?><input type="hidden" name="freelancer_id" value="<?= e($freelancer['user_id']) ?>"><label>پروژه<select name="job_id" required><?php foreach ($jobs as $job): if ($job['status'] === 'open'): ?><option value="<?= e($job['id']) ?>"><?= e($job['title']) ?></option><?php endif; endforeach; ?></select></label><label>مبلغ پیشنهادی<input type="number" name="proposed_amount" min="1" step="0.01" required placeholder="دلار"></label><label>پیام همکاری<textarea name="message" rows="3" required placeholder="پیام شما برای این متخصص..."></textarea></label><button class="button" type="submit">ارسال دعوت</button></form></details><?php endif; ?></article><?php endforeach; ?><?php if (!$freelancers): ?><p class="empty-state">فریلنسر فعالی برای نمایش وجود ندارد.</p><?php endif; ?></div></section>
  <section class="dash-card" id="invitations"><div class="card-title"><h2>دعوت‌های همکاری من</h2></div><?php foreach ($invitations as $invitation): ?><div class="proposal-row"><strong><?= e($invitation['freelancer_name']) ?> · <?= e($invitation['title']) ?></strong><span><?= e($invitation['proposed_amount']) ?> دلار · <?= e($invitationLabels[$invitation['status']] ?? $invitation['status']) ?></span></div><?php endforeach; ?><?php if (!$invitations): ?><p class="muted">هنوز دعوت همکاری ارسال نکرده‌اید.</p><?php endif; ?></section>
</section>
