<?php
declare(strict_types=1);
final class Proposal extends Model
{
	public function forFreelancer(int $userId): array { $s = $this->db->prepare('SELECT pr.*, j.title FROM proposals pr INNER JOIN jobs j ON j.id = pr.job_id WHERE pr.freelancer_id = :user_id ORDER BY pr.created_at DESC'); $s->execute(['user_id' => $userId]); return $s->fetchAll(); }
	public function create(int $userId, int $jobId, string $coverLetter, float $bidAmount): void { $s = $this->db->prepare('INSERT INTO proposals (job_id, freelancer_id, cover_letter, bid_amount) VALUES (:job_id, :user_id, :cover_letter, :bid_amount)'); $s->execute(['job_id' => $jobId, 'user_id' => $userId, 'cover_letter' => $coverLetter, 'bid_amount' => $bidAmount]); }
	public function forEmployer(int $employerId): array { $s=$this->db->prepare('SELECT pr.*,j.title,p.display_name AS freelancer_name,p.headline FROM proposals pr INNER JOIN jobs j ON j.id=pr.job_id LEFT JOIN profiles p ON p.user_id=pr.freelancer_id WHERE j.employer_id=:employer_id ORDER BY pr.created_at DESC'); $s->execute(['employer_id'=>$employerId]); return $s->fetchAll(); }
	public function updateStatus(int $proposalId,int $employerId,string $status): void { $this->db->beginTransaction(); try { $s=$this->db->prepare("SELECT pr.job_id,pr.freelancer_id,pr.bid_amount FROM proposals pr INNER JOIN jobs j ON j.id=pr.job_id WHERE pr.id=:id AND j.employer_id=:employer_id FOR UPDATE"); $s->execute(['id'=>$proposalId,'employer_id'=>$employerId]); $proposal=$s->fetch(); if(!$proposal) throw new RuntimeException('Proposal not found.'); $this->db->prepare('UPDATE proposals SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$proposalId]); if($status==='accepted'){ $this->db->prepare("UPDATE proposals SET status='rejected' WHERE job_id=:job_id AND id<>:id AND status='pending'")->execute(['job_id'=>$proposal['job_id'],'id'=>$proposalId]); $this->db->prepare("UPDATE jobs SET status='in_progress' WHERE id=:job_id")->execute(['job_id'=>$proposal['job_id']]); $this->db->prepare("INSERT INTO contracts (job_id,employer_id,freelancer_id,status,total_amount) VALUES (:job_id,:employer_id,:freelancer_id,'active',:amount)")->execute(['job_id'=>$proposal['job_id'],'employer_id'=>$employerId,'freelancer_id'=>$proposal['freelancer_id'],'amount'=>$proposal['bid_amount']]); $contractId=(int)$this->db->lastInsertId(); $rate=(float)($this->db->query("SELECT setting_value FROM platform_settings WHERE setting_key='commission_rate'")->fetchColumn()?:10); $this->db->prepare('INSERT INTO platform_commissions (contract_id,employer_id,freelancer_id,gross_amount,rate,commission_amount) VALUES (:contract_id,:employer_id,:freelancer_id,:gross_amount,:rate,:commission_amount)')->execute(['contract_id'=>$contractId,'employer_id'=>$employerId,'freelancer_id'=>$proposal['freelancer_id'],'gross_amount'=>$proposal['bid_amount'],'rate'=>$rate,'commission_amount'=>round($proposal['bid_amount']*$rate/100,2)]); } $this->db->commit(); } catch(Throwable $e){$this->db->rollBack();throw $e;} }
	public function addMessage(int $proposalId,int $employerId,string $body): void { $s=$this->db->prepare('INSERT INTO proposal_messages (proposal_id,sender_id,body) SELECT pr.id,:sender_id,:body FROM proposals pr INNER JOIN jobs j ON j.id=pr.job_id WHERE pr.id=:proposal_id AND j.employer_id=:employer_id'); $s->execute(['proposal_id'=>$proposalId,'sender_id'=>$employerId,'body'=>$body]); if($s->rowCount()<1) throw new RuntimeException('Proposal not found.'); }
	public function messagesForEmployer(int $employerId): array { $s=$this->db->prepare('SELECT pm.*,pr.id AS proposal_id FROM proposal_messages pm INNER JOIN proposals pr ON pr.id=pm.proposal_id INNER JOIN jobs j ON j.id=pr.job_id WHERE j.employer_id=:employer_id ORDER BY pm.created_at DESC'); $s->execute(['employer_id'=>$employerId]); return $s->fetchAll(); }
}
